allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
overrides:
  "@auth/core": "0.41.1"
  "next@>=16.0.0-canary.0 <16.0.7": ">=16.0.7"
